services:
    surfnet_conext_operations_support.verification_runner:
        class: Surfnet\Conext\EntityVerificationFramework\Runner
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata.janus
            - @surfnet_conext_operations_support.repository.published_metadata.guzzle
            - @surfnet_conext_operations_support.verification_blacklist
            - @logger

    surfnet_conext_operations_support.repository.configured_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyConfiguredMetadataRepository

    surfnet_conext_operations_support.repository.configured_metadata.janus:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\JanusConfiguredMetadataRepository
        arguments:
            - @surfnet_janus_api_client.service.api
            - @logger

    surfnet_conext_operations_support.repository.published_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyPublishedMetadataRepository

    surfnet_conext_operations_support.repository.published_metadata.guzzle:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\GuzzlePublishedMetadataRepository
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata.janus
            - @surfnet_conext_operations_support.repository.guzzle.published_metadata
            - @logger

    surfnet_conext_operations_support.repository.guzzle.published_metadata:
        class: GuzzleHttp\Client

    surfnet_conext_operations_support.repository.jira_report:
            class: Surfnet\Conext\OperationsSupportBundle\Repository\JiraReportRepository
            factory: [@doctrine.orm.entity_manager, getRepository]
            arguments:
                - 'Surfnet\Conext\OperationsSupportBundle\Entity\JiraReport'

    surfnet_conext_operations_support.command.run_suites:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\RunSuitesCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.verification_blacklist:
        class: Surfnet\Conext\EntityVerificationFramework\Blacklist
        factory: [Surfnet\Conext\EntityVerificationFramework\BlacklistFactory, 'fromDescriptors']
        arguments:
            - # Set of entities per suite or test name, see extension
            - # Set of entities to blacklist for all suites or test names, see extension

    surfnet_conext_operations_support.service.jira_report:
        class: Surfnet\Conext\OperationsSupportBundle\Service\JiraReportService
        arguments:
            - @surfnet_conext_operations_support.repository.jira_report
            - @logger

    surfnet_conext_operations_support.service.jira_issue:
        class: Surfnet\Conext\OperationsSupportBundle\Service\JiraIssueService
        arguments:
            - ~ # Issue API service, yet to implement in JiraApiClientBundle
            - # Status mapping
            - # Priority mapping
            - @logger
