services:
    surfnet_conext_operations_support.verification_runner:
        class: Surfnet\Conext\EntityVerificationFramework\Runner
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata.janus
            - @surfnet_conext_operations_support.verification_blacklist
            - @surfnet_conext_operations_support.context_factory
            - @logger

    surfnet_conext_operations_support.context_factory:
        public: false
        class: Surfnet\Conext\EntityVerificationFramework\ContextFactory
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata
            - @surfnet_conext_operations_support.repository.published_metadata
            - @surfnet_conext_operations_support.guzzle.test_client

    surfnet_conext_operations_support.repository.configured_metadata:
        public: false
        alias: surfnet_conext_operations_support.repository.configured_metadata.janus

    surfnet_conext_operations_support.repository.configured_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyConfiguredMetadataRepository

    surfnet_conext_operations_support.repository.configured_metadata.janus:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\JanusConfiguredMetadataRepository
        arguments:
            - @surfnet_janus_api_client.service.api
            - @logger

    surfnet_conext_operations_support.repository.published_metadata:
        public: false
        alias: surfnet_conext_operations_support.repository.published_metadata.guzzle

    surfnet_conext_operations_support.repository.published_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyPublishedMetadataRepository

    surfnet_conext_operations_support.repository.published_metadata.guzzle:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\GuzzlePublishedMetadataRepository
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata.janus
            - @surfnet_conext_operations_support.repository.guzzle.published_metadata
            - @logger

    surfnet_conext_operations_support.repository.guzzle.published_metadata:
        class: GuzzleHttp\Client

    surfnet_conext_operations_support.repository.jira_report:
            class: Surfnet\Conext\OperationsSupportBundle\Repository\JiraReportRepository
            factory: [@doctrine.orm.entity_manager, getRepository]
            arguments:
                - 'Surfnet\Conext\OperationsSupportBundle\Entity\JiraReport'

    surfnet_conext_operations_support.command.run_suites:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\RunSuitesCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.command.jira_issue_statuses:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\JiraIssueStatusesCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.command.jira_issue_priorities:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\JiraIssuePrioritiesCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.command.jira_issue_types:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\JiraIssueTypesCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.command.jira_projects:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\JiraProjectsCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.command.jira_issue_view:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\JiraIssueViewCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.command.jira_my_permissions:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\JiraMyPermissionsCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.verification_blacklist:
        class: Surfnet\Conext\EntityVerificationFramework\Blacklist
        factory: [Surfnet\Conext\EntityVerificationFramework\BlacklistFactory, 'fromDescriptors']
        arguments:
            - # Set of entities per suite or test name, see extension
            - # Set of entities to blacklist for all suites or test names, see extension

    surfnet_conext_operations_support.service.jira_report:
        class: Surfnet\Conext\OperationsSupportBundle\Service\JiraReportService
        arguments:
            - @surfnet_conext_operations_support.repository.jira_report
            - @logger

    surfnet_conext_operations_support.service.jira_issue:
        class: Surfnet\Conext\OperationsSupportBundle\Service\JiraIssueService
        arguments:
            - @surfnet_jira_api_client.service.issue
            - # Status mapping
            - # Priority mapping
            - @logger

    surfnet_conext_operations_support.reporter.jira:
        class: Surfnet\Conext\OperationsSupportBundle\Reporter\JiraReporter
        arguments:
            - @surfnet_conext_operations_support.service.jira_report
            - @surfnet_conext_operations_support.service.jira_issue
            - @surfnet_conext_operations_support.factory.ramsey_uuid
            - @logger

    surfnet_conext_operations_support.factory.ramsey_uuid:
        class: Ramsey\Uuid\UuidFactory

    surfnet_conext_operations_support.guzzle.test_client:
        public: false
        class: GuzzleHttp\Client
        arguments:
            - handler: @surfnet_conext_operations_support.guzzle.test_client.handler_stack
              exceptions: false

    surfnet_conext_operations_support.guzzle.test_client.handler_stack:
        public: false
        class: GuzzleHttp\HandlerStack
        factory: [GuzzleHttp\HandlerStack, 'create']
        calls:
            - [ push, [@surfnet_conext_operations_support.guzzle.test_client.middleware.logging] ]

    surfnet_conext_operations_support.guzzle.test_client.middleware.logging:
        public: false
        class: Surfnet\Conext\OperationsSupportBundle\Guzzle\Middleware\LoggingMiddleware
        arguments:
            - @logger
