services:
    surfnet_conext_operations_support.verification_runner:
        class: Surfnet\Conext\EntityVerificationFramework\Runner
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata.janus
            - @surfnet_conext_operations_support.repository.published_metadata.dummy
            - @surfnet_conext_operations_support.verification_blacklist
            - @logger

    surfnet_conext_operations_support.repository.configured_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyConfiguredMetadataRepository

    surfnet_conext_operations_support.repository.configured_metadata.janus:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\JanusConfiguredMetadataRepository
        arguments:
            - @surfnet_janus_api_client.service.api
            - @logger

    surfnet_conext_operations_support.repository.published_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyPublishedMetadataRepository

    surfnet_conext_operations_support.command.run_suites:
        class: Surfnet\Conext\OperationsSupportBundle\Console\Command\RunSuitesCommand
        tags:
            -  { name: console.command }

    surfnet_conext_operations_support.verification_blacklist:
        class: Surfnet\Conext\EntityVerificationFramework\Blacklist
        factory: [Surfnet\Conext\EntityVerificationFramework\VerificationBlacklistFactory, 'fromDescriptors']
        arguments:
            - [] # Set of entities per suite or test name, see extension
            - {} # Set of entities to blacklist for all suites or test names, see extension
