services:
    surfnet_conext_operations_support.verification_runner:
        class: Surfnet\Conext\EntityVerificationFramework\Runner
        arguments:
            - @surfnet_conext_operations_support.repository.configured_metadata.dummy
            - @surfnet_conext_operations_support.repository.published_metadata.dummy
            - @logger

    surfnet_conext_operations_support.repository.configured_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyConfiguredMetadataRepository

    surfnet_conext_operations_support.repository.published_metadata.dummy:
        class: Surfnet\Conext\OperationsSupportBundle\Repository\DummyPublishedMetadataRepository
