services:
  surfnet_janus_api_client.guzzle:
    class: GuzzleHttp\Client
    arguments:
      - "" # Client configuration
    public: false

  surfnet_janus_api_client.service.api:
    public: false4
    class: Surfnet\JanusApiClientBundle\Service\ApiService
    arguments:
      - @surfnet_janus_api_client.guzzle
