imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

monolog:
    handlers:
        stream:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  DEBUG

swiftmailer:
    disable_delivery: true

surfnet_conext_operations_support:
    suites: []
