imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

monolog:
    handlers:
        syslog:
            type:     syslog
            ident:    conext-operations-support
            facility: user
        console:
            type: console
